### ISSUE TITLE
android project sample needed

### ISSUE THREAD

**Issue by xiaozhubenben** [pexip/pexkit-sdk#1]
hi,
Please upload sample for android ,and  documents ,thanks.

I develop android app using Eclipse ADT, not android studio.
After unpack the aar file ,add lib and jars to my eclipse projects, 
create conference object, and invoked  connect method. it throwed a class not found exception :

10-15 11:22:07.481: E/AndroidRuntime(21393): Caused by: java.lang.NoClassDefFoundError: com.spotify.dns.DnsSrvResolvers

DId i miss any library jar here?

**Comment by ianmorty** [comment]
Hi !

Thanks for the downloading the SDK and giving it a go.  We use Android Studio for our examples and everything seems to work fine here. I'll see if I can figure out what's happening in eclipse for you.

**Comment by hanimustafa** [comment]
Luke,

Can you make sure that you have this in your settings.gradle?

include ':app', ':pexkit'

Regards

~Hani Mustafa

**Comment by xiaozhubenben** [comment]
HI, Hani Mustafa,Ian Mortimer.
     Thanks a lot. I had download your Android Sample ,and adaptered to Eclipse Project,and successly run on my Samsung Note3 (Android 5.0),but failed on  Samsung S4(android 4.4.2).
this is  exception log:
10-16 11:20:44.721: E/AndroidRuntime(6498): java.lang.RuntimeException: createContext failed: EGL_BAD_CONFIG
10-16 11:20:44.721: E/AndroidRuntime(6498): 	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1201)
10-16 11:20:44.721: E/AndroidRuntime(6498): 	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1192)
10-16 11:20:44.721: E/AndroidRuntime(6498): 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1042)
10-16 11:20:44.721: E/AndroidRuntime(6498): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1409)
10-16 11:20:44.721: E/AndroidRuntime(6498): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

Althought sample app can ran on Samsung Note3, but  seemed not stable ,and video quality is poor, is there any API functions we can improve it ?

----------------------------------
BTW:
For those who using Eclipse ADT and not use Gradle :
and these jar to your lib,
1、android-async-http-1.4.8.jar
2、dns lib and its dependencies
http://mvnrepository.com/artifact/com.spotify/dns/3.0.2

**Comment by ianmorty** [comment]
Thanks for that @xiaozhubenben - will update the README for the eclipse settings.  As for video quality on the phones - are the cameras the same ?  are there other differences between the phones ?  Our SDK negotiates the same SDP settings regardless of phone type.

**Comment by ianmorty** [comment]
@xiaozhubenben i'm going to close this issue now that you have got a working example.  Feel free to let us know in the comments how you're getting on.

**Comment by xiaozhubenben** [comment]
Hi,
It seemed samsung S4 cannot run example app. same error as 
http://stackoverflow.com/questions/26504742/open-gl-bad-config-error-on-samsung-s4

And the video quality, I mean , can I change the video resolution(CIF or VGA or SVGA ..) through a SDK  interface?

thanks.
