### ISSUE TITLE
how to get myself role?

### ISSUE THREAD

**Issue by xiaozhubenben** [pexip/pexkit-sdk#10]
hi,
  i am using android pexkit sdk . 
  after login  a  vmr , how can I get my role in this conference (I mean, i am host or guest)?

**Comment by wuurrd** [comment]
I would suggest something like:

        String role = null;
        for (Participant p: conference.getParticipants()) {
            if (p.uuid == conference.getUUID())
                role = p.role;
        }
        return role;
