### ISSUE TITLE
[Android] switchCamera does not keep camera / microphone muted

### ISSUE THREAD

**Issue by gblachonupg** [pexip/pexkit-sdk#11]
On Android app, if i change the camera used for selfview, it unmute all mic and cam previously mute by the participant

**Comment by misu-rg** [comment]
I still have some issues with this.

Microphone is not correctly muted/unmuted when switching camera selfview.
It seems that mic takes the same value as the camera.

If camera is muted, microphone will be muted as well when switching camera, even if it was unmuted.
