### ISSUE TITLE
[Android] Selfview positioning

### ISSUE THREAD

**Issue by gblachonupg** [pexip/pexkit-sdk#12]
When I position the selfview at origins (0,0), its not on Top-Left of the screen as it should.

**Comment by wuurrd** [comment]
I can not reproduce this - 

when calling pexkit.moveSelfview(0, 0, 25, 25) It's a the top-left of the screen.

Please show example code that doesn't work -

if you used pexkit.moveSelfview(0,0,0,0) that's the same as hiding selfview.

**Comment by misu-rg** [comment]
It seems the problem has been corrected by updating to the latest version of the PexKit SDK.

Thanks.
