### ISSUE TITLE
[ANDROID] VMR join as Guest without Guest PIN

### ISSUE THREAD

**Issue by gblachonupg** [pexip/pexkit-sdk#13]
If we create a Virtual Room like that :
     - Host PIN : 444
     - Allow Guests : True
     - Guest PIN : None

It is impossible to join as Guest using the SDK (It works if we use the host pin). We get the following error :

01-20 10:14:33.540 11866-11866/com.g2j.app E/pexkit.requestToken: returned 403 with body {"status":"success","result":{"version":{"pseudo_version":"26902.0.0","version_id":"11"},"guest_pin":"none","pin":"required"}} exception org.apache.http.client.HttpResponseException: Forbidden
01-20 10:14:33.540 11866-11866/com.g2j.app I/pexkit.requestToken: requestToken can support pin-less guest or host with pin
 
AND:
 
01-20 10:14:33.600 11866-12472/com.g2j.app I/pexkit.EventSource: (https://fr-px1.g2j.vc:443/api/client/v2/conferences/123456@g2j.vc/events) GET responded with 403
01-20 10:14:33.600 11866-12472/com.g2j.app W/System.err: java.io.FileNotFoundException: https://fr-px1.g2j.vc:443/api/client/v2/conferences/123456@g2j.vc/events
01-20 10:14:33.600 11866-12472/com.g2j.app W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:197)
01-20 10:14:33.600 11866-12472/com.g2j.app W/System.err:     at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
01-20 10:14:33.600 11866-12472/com.g2j.app W/System.err:     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
01-20 10:14:33.600 11866-12472/com.g2j.app W/System.err:     at com.pexip.pexkit.EventSource$1.run(EventSource.java:68)

**Comment by wuurrd** [comment]
To join a conference without guest_pin, just join with pin = "none"

That should fix your issues.
