### ISSUE TITLE
[Android] Participant mute cam

### ISSUE THREAD

**Issue by gblachonupg** [pexip/pexkit-sdk#14]
I don't find a way to mute participants' cam using the Android SDK

**Comment by wuurrd** [comment]
To mute your camera do:
conference.setVideoMute(true)

And to unmute do:
conference.setVideoMute(false)

- to check the status, do conference.getVideoMute()

(same thing for audio with conference.getAudioMute/setAudioMute)

**Comment by xiaozhubenben** [comment]
I  think he want to mute other particpant 's video, not only self video.

**Comment by gblachonupg** [comment]
Yes please

**Comment by wuurrd** [comment]
Muting another participant's video is not possible in the pexip platform.
