### ISSUE TITLE
[Android] Hardware-specific issue with webrtc/GLSurfaceView

### ISSUE THREAD

**Issue by Korganiof** [pexip/pexkit-sdk#16]
The video is correctly sent to the VMR, and the selfview is crystal clear, but the GLSurfaceView is really distorted on Samsung Galaxy Tab A. Same program tested on Samsung Galaxy Tab 4 did not reproduce the distortion. After some digging around I found this: https://bugs.chromium.org/p/webrtc/issues/detail?id=4787 - the distorted image is similar to mine and it seems the problem is with webrtc rendering (stretching the resolution). Is there a workaround using PexKit or do we have to wait for webrtc dev's to react?

**Comment by wuurrd** [comment]
Can you give some more info on how to reproduce - might be we could do something smart like use texture decoding (as mentioned in the bug)

**Comment by Korganiof** [comment]
We used the code that is used to connect to a working VMR exactly like in the example one. The problem seems to be happening in Samsung Tab A tablet, but not in Samsung Tab 4. When we call (using the pexip client) from TabA to Tab4 the video works just fine.

**Comment by ianmorty** [comment]
These SDK's are now deprecated and i'd suggest moving over to the new methods as outlined in the guides thus giving you full control over every aspect of the connection.
