### ISSUE TITLE
IOS problem on upload to app store

### ISSUE THREAD

**Issue by StevenCosairus** [pexip/pexkit-sdk#19]
After implementing the PexKit.Framework into my project. I built an archive copy validated it tried to upload to the App Store. During the Submitting archive to the iOS app store i get errors indicating Unsupported Architectures, Invalid Segment Alignment, ect. I have attached the screen shot of the errors returned. If i remove the PexKit.Framework and all supporting code the submission works without a problem.
![screen shot 2016-02-09 at 9 15 12 am](https://cloud.githubusercontent.com/assets/17147385/12927118/70965b8a-cf34-11e5-9d5d-d19fa11a9048.png)

**Comment by ianmorty** [comment]
Hi @StevenCosairus - the SDK we produce contains binaries suitable for use with simulators.  Please try the release version of the SDK in your project and try submitting with that instead.

**Comment by StevenCosairus** [comment]
thanks for the update. I have downloaded release version of the SDK add the pexKit-release.framework to the embedded binaries.  But when i compile it i get a linker error "framework not found PexKit-release".  I have verified the location to the release framework is the same as the previous one.  What am i missing?

**Comment by StevenCosairus** [comment]
I have it figured it out.  I had to rename the PexKit-release.framework to Pexkit.framework then remove the simulator framework replacing it with the newly renamed version.  Then the linker error goes away and the upload works and the conferencing logic works once downloaded from test flight.  Thanks for your help.

**Comment by ianmorty** [comment]
excellent @StevenCosairus .  let us know if you need any more help with your app or testing your app.  I'll close this issue now.
