### ISSUE TITLE
Android client API information required

### ISSUE THREAD

**Issue by priyaekbote** [pexip/pexkit-sdk#2]
Can you please provide class or method names to be used in android. Or android demo application source code demonstrating video conferencing.

**Comment by ianmorty** [comment]
Hi,

Thanks for taking the time to look at the SDK.  For a quick introduction to the general layout of the API, take a look in the documentation section.  Although they look like iOS specific, the core concepts and naming are the same in both SDK's (e.g. using a conference object to connect, requestToken etc)

For example, in your MainActivity define a conference object, create it, connect and request a token - take a look at https://gist.github.com/ianmorty/9289815ad6891ae06b44 for some pointers.

We'll be adding more examples and documentation as time goes on.

**Comment by ianmorty** [comment]
Hi @priyaekbote, we now have a sample application for you to try.  I'll close this issue now but feel free to let us now in the comments how you're getting on.
