### ISSUE TITLE
Need more info

### ISSUE THREAD

**Issue by ostapkuzyk** [pexip/pexkit-sdk#22]
Hello Ian!

Could you please explain in more details how to properly initiate call/video call and allowing user(GUEST) to participate in conference. Which methods to use.

Thanks in advance

**Comment by ianmorty** [comment]
Response in out-of-band email.  For others benefit:

Call initiation is handled as per the demo video.  First, you create a
conference object with your conference information (URI, PIN etc).  From
that object you can then request a token.  Once you have a token you can
start listening for the event stream and also escalate media.
