### ISSUE TITLE
How could I use this framework into my object-c base project?

### ISSUE THREAD

**Issue by vhikd** [pexip/pexkit-sdk#23]
My project was create long time ago with object-c. I want to use this framework with the video function.
When I import the framework into my project, I even can't run the app.It comes out the error like 
dyld: Library not loaded: @rpath/PexKit.framework/PexKit
  Referenced from: /var/containers/Bundle/Application/320B17E0-7F4E-4643-9D10-1564A5401197/xxxxxx.app/xxxxxx
  Reason: image not found

Any advise to solve this problem?

**Comment by ianmorty** [comment]
Hi @vhikd,  the SDK is written in Swift but we do expose the required parts of the SDK to Objective-C.  Are you sure you are embedding the SDK properly in your project (embedded binaries).  Unfortunately, we can't offer more in-depth developer support for objective-c projects.

**Comment by vhikd** [comment]
@ianmorty  Thanks for your reply. I always embedding the SDK at the first time. Unfortunately, nothing will change. But when I changed the link status of the framework to optional, the project will build success and everything looks like goes on. And the connect method will never be called.

So, after all , I will re-write the project with swift.
