### ISSUE TITLE
[iOS] Provide some flexibility for setting conference aliases 

### ISSUE THREAD

**Issue by miguelsanchez** [pexip/pexkit-sdk#27]
Currently on iOS, conference aliases are created based on a conferenceURI that is initialized with a conference ID and a host:

`let uri = ConferenceURI(conference: "535326134", host: "node.com")`

Once created, after connecting to the conference when we try to request a token it doesn't work because the POST request uses a conference alias in the form of `<confID@node>` whereas our server accepts `<confID>` and thus the request fails as follows:

`About to post to /api/client/v2/conferences/535326134@node.com/request_token?display_name=miguel`

`REQUEST TOKEN RESPONSE {
    result = "Neither conference nor gateway found";
    status = failed;
}`

We have observed this same issue in both iOS and Android but we have also checked that we can get the token if we used the right form of the conference alias for our server (`<confID>`) instead of the one including the node (`<confID@node>`)

Could the SDK be modified to be more flexible so that we can specify this preferred conference alias definition?

Thanks in advance

**Comment by zaichang** [comment]
I echo this feature request for the Android side. At the moment the Pexip server we're working with only has conference aliases that corresponds to ```<conference-id>```

On Android I was able to connect to the video conference if I do some reflection to set the conference id manually to not include the ```@<node>``` portion:

    import java.lang.reflect.Field;

    this.conference = new Conference("Android Hack", new URI("918728444@pexip-node.our-company.com"), "");

    Field field = Conference.class.getDeclaredField("conference");
    field.setAccessible(true);
    field.set(this.conference, "913826134");

but it would be much preferable not to do so...

(disclaimer: Miguel and I are on the same dev team)

**Comment by wuurrd** [comment]
@zaichang send an email to sdk@pexip.com and we can take this issue further

**Comment by wuurrd** [comment]
Modifying this to only be valid for iOS as it already works for android (thanks for the patch!)

**Comment by ianmorty** [comment]
available now as the `useOnlyConferenceIdForRequests` flag on the conference object in 7.7.2 of iOS SDK
