### ISSUE TITLE
framework not working in Swift

### ISSUE THREAD

**Issue by bens12** [pexip/pexkit-sdk#3]
/Users/IphoneDeveloper/Desktop/training/IOS Swift/videoConferencing/videoConferencing/AppDelegate.swift:11:8: Module file was created by a newer version of the compiler: /Users/IphoneDeveloper/Desktop/training/IOS Swift/videoConferencing/PexKit.framework/Modules/PexKit.swiftmodule/x86_64.swiftmodule

why this error happens ?
i am using xcode 6.2 after upgrading to xcode 7.0 also this error occurs.

**Comment by ianmorty** [comment]
what version of Xcode are you running ?

**Comment by ianmorty** [comment]
sorry - saw comment - try 7.1

**Comment by bens12** [comment]
this error is due to xcode version mismatch ?

**Comment by ianmorty** [comment]
potentially, the signature looks similar.  try cleaning your project, deleting your derived data folder and building again.

**Comment by bens12** [comment]
I tried in xcode 7.1 also same error occurred.

**Comment by ianmorty** [comment]
i'll rebuild the demo app locally and push any changes if they're needed

**Comment by bens12** [comment]
ok, thanks for your support.

**Comment by ianmorty** [comment]
try the latest kit i've pushed with xcode 7.1 and make sure you clean your project / derived data just to be sure it's nothing funny with cached data.

**Comment by bens12** [comment]
Ian i have successfully imported ,but when enter the URI i can hear only the audio video is not displayed.Can u spot out wether the issue is in my side or your side.

**Comment by bens12** [comment]
![screen shot 2015-10-24 at 10 19 36 am](https://cloud.githubusercontent.com/assets/13806582/10708936/ff22ac92-7a38-11e5-9497-d9f869bd6b64.png)

**Comment by ianmorty** [comment]
You're using s simulator which has no video. The MCU is sending back a broken camera icon to indicate its not receiving anything. The app is working fine now.
