### ISSUE TITLE
Issue with Android example program. 

### ISSUE THREAD

**Issue by bhavanimogili** [pexip/pexkit-sdk#30]
Could you please create a video for android app as well as like ios. Not able to implement the example program correctly. it throws error no such instance variable.

**Comment by bhavanimogili** [comment]
Could someone provide me with details to run the example program correctly. Any documentation or video should help.

**Comment by wuurrd** [comment]
Hi, sorry for the late reply. The new example is at https://github.com/pexip/pexkit-android-example
