### ISSUE TITLE
tvOS

### ISSUE THREAD

**Issue by miguelsanchez** [pexip/pexkit-sdk#31]
Are there any plans on releasing an SDK built for tvOS? We'd like to experiment with an Apple TV client.
Thanks.

**Comment by ianmorty** [comment]
Currently no plans for this.  What exactly did you have i mind with e.g. support for cameras etc ?

Ian.

**Comment by miguelsanchez** [comment]
Our initial plan was to use an IP camera as video input for the Apple TV and use Pexip to connect to the conference and receive the video stream as our mobile clients can do at the moment.

**Comment by ianmorty** [comment]
I'm going to close this as it's not really an issue, more of a request for information.
