### ISSUE TITLE
suggestion of conference construstor 

### ISSUE THREAD

**Issue by rinvay** [pexip/pexkit-sdk#32]
in android version, Conference has constructor `Conference(String displayName, URI uri, String pin)`, and resolve uri to set uri as conference name, and set domain part of uri as host.

there may be problem if the specific URI with domain  is not added into the list of aliases or domain of uri is not the real host

suggust that: 
  divide uri into two params: conferenceName and host for more  convenience

there is the same problem in ios sdk

**Comment by wuurrd** [comment]
This was fixed in #27 - there is now a setConferenceName that can be used after the constructor is called.
