### ISSUE TITLE
iOS(Swift) videoView screen become black after returning to conference

### ISSUE THREAD

**Issue by coucouParis** [pexip/pexkit-sdk#33]
Hello,

I wan to let video on pause , for example : 
When I am in a conference, I click button "home" in my iPhone. After this, I want to return to my conference, but after clicking the icon of application and returning to the conference, the videoView become black, only videoSelfView still works...

Do you some suggestions to let videoView work like videoSelfView after returning to the conference?
Do you some fonctions in SDK to let videoView on pause after "home" pressed? Thank you.

**Comment by ivanbellalopez** [comment]
I have experienced the same issue. After bringing the app to foreground it keeps sending video/audio but not receiving.

**Comment by ivanbellalopez** [comment]
I also noticed the same issue using the Pexip Infinity Connect

**Comment by ianmorty** [comment]
This is a known issue at the moment with the current WebRTC implementation.  We're looking at ways of improving this in the future.  Will close this and post updates to interested parties.

**Comment by ivanbellalopez** [comment]
Thanks @ianmorty. Please keep us posted.

**Comment by xiefangzhenz** [comment]
Whether the question already did solve？

**Comment by miguelsanchez** [comment]
Any updates on this? If this is a known issue I guess it should stay open until it is resolved.

**Comment by jfowens** [comment]
This is still an issue with the native Pexip app and we are currently investigating ways in which we can resolve it. That being said, you can work around the issue with the SDK by automating the app to re-join the same conference and re-initialize the media stack. Some of our partners have already done this within their apps posted on the app store.

**Comment by xiefangzhenz** [comment]
now  we are re-join the same conference and re-initialize the media stack.....thanks
