### ISSUE TITLE
IOS pexip module issue

### ISSUE THREAD

**Issue by bmogili-involve** [pexip/pexkit-sdk#35]
Hi 
I have Xcode 7.3.1 and Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
Target: x86_64-apple-macosx10.9. I am trying the video tutorial example. But build fails with error below:

/Users/ivc-war-mac2/Documents/PexipDemo/PexipDemo/PexipDemo/ViewController.swift:9:8: Module file was created by an older version of the compiler; rebuild 'PexKit' and try again: /Users/ivc-war-mac2/Documents/PexipDemo/PexipDemo/PexKit.framework/Modules/PexKit.swiftmodule/x86_64.swiftmodule

Please help. Thanks. To be specific I am a developer working for involve Warrington and trying to use pexip to rebrand a app.

**Comment by ianmorty** [comment]
Closing this as resolved by downloading the correct PexKit installation in developer environment.

**Comment by bmogili-involve** [comment]
Yes sure Ian. Thanks a lot for all the support. Have a nice day!

Regards
Bhavani
