### ISSUE TITLE
[Android] documentarion

### ISSUE THREAD

**Issue by icarnico** [pexip/pexkit-sdk#36]
will this library has a useful android documentation? I just found it for Swift and a kind of "example" in android without any kind of something we can call usefull.

Its suposed to be really similar to iOS framework. In what moment did you think that? the conference object is a bad copy of the iOS framework and nothing is where its suposed to be, the protocols where translated to java AS CLASSES?? WTF were you thinking????

**Comment by nicolascormier** [comment]
@icarnico feel free to reach out directly to us at sdk@pexip.com
