### ISSUE TITLE
[android] answer a call from a conference

### ISSUE THREAD

**Issue by rinvay** [pexip/pexkit-sdk#37]

**Comment by wuurrd** [comment]
Hi,

You can use the new Registration code.

```
Registration reg = new Registration(username, password, alias, hostname);
reg.setDelegate(new RegistrationDelegate() { ... });
reg.requestToken(closure);
...
reg.listenForEvents();
...
```

**Comment by rinvay** [comment]
I know, then I will receive an incomingcall event by 
   
    onIncomingCall(String conferenceAlias, String serviceType, String token) 

of `RegistrationDelegate `, then, how to join then incoming conference? as a normal participant? is the `token` in that method useful?

**Comment by rinvay** [comment]
there is no method like `rejectCall`, how does the conference know i accept the call?
