### ISSUE TITLE
Can provide support for Object-C PexipKit.framework iOS7.0

### ISSUE THREAD

**Issue by MGXu** [pexip/pexkit-sdk#39]
Can provide support for Object-C PexipKit.framework iOS7.0

**Comment by jfowens** [comment]
Hi - 

Although the PexKit SDK is built using Swift, all of the feature/functionality can be done in Objective C, if desired. All functions within the SDK have a corresponding Objective C compliment and they are documented within the SDK itself. 

We do highly recommend to all of our development partners that you migrate your apps from Objective C towards Swift based on Apple's guidance and continued movement away from Objective C. 

Hope this helps.

**Comment by MGXu** [comment]
Thank you for your reply, please allow me to ask a question, you provide examples of code with the new static library does not match, can provide the latest example code, thank you very much. I'm sorry I did not find the IOS mobile terminal interface documentation
