### ISSUE TITLE
Android Code Importing in Eclipse

### ISSUE THREAD

**Issue by jackson-therasoft** [pexip/pexkit-sdk#4]
Hi, I am using Eclipse. I have extracted the .aar file and got the classes.jar file. And I have imported the .jar file in my example project on eclipse. I have also added android-async-http-1.4.9.jar and dns-3.0.2.jar files.

It shows this error.

![screen](https://cloud.githubusercontent.com/assets/15318362/10721614/c7a00cfc-7bcc-11e5-88a4-416e56aba5ef.png)

Please assist me to get out of this issue.
Or If possible please give me an example as Eclipse project file.

**Comment by jackson-therasoft** [comment]
Hi, I have succeeded to build the sample code.

But i am getting this error while run on my android phone.

10-26 11:04:41.426: E/AndroidRuntime(13192): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pexip/pexkit/Conference;
10-26 11:04:41.426: E/AndroidRuntime(13192): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pexip.pexkit.Conference" on path: DexPathList[[zip file "/data/app/com.pexip.example-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
10-26 11:04:41.426: E/AndroidRuntime(13192): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-26 11:04:41.426: E/AndroidRuntime(13192): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

Please help.

**Comment by hanimustafa** [comment]
Make sure your settings.gradle look like this:

include ':app', ':pexkit'


On Mon, Oct 26, 2015 at 6:40 AM, jackson-therasoft <notifications@github.com

**Comment by jackson-therasoft** [comment]
I'm not using Android Studio, i'm using Eclipse. Can you please provide us an example as eclipse project file.

**Comment by xiaozhubenben** [comment]
hi，
I had compiled with Eclipse successfully.
please check your libs  :  
Did you add these jars to libs?

libjingle_peerconnection.jar( it located in libs  at aar file)
pexipRTC.jar( it is classes.jar in aar file,I renamed it)
json-simple-1.1.1.jar( it located in libs  at aar file)
android-async-http-1.4.8.jar
dns-3.0.2.jar
dnsjava-2.1.7.ja
guava-18.0.jar
jsr305-3.0.1.jar
slf4j-api-1.7.12.jar

**Comment by jackson-therasoft** [comment]
Thank you xiaozhubenben,

It works for me now.

Previously i had android-async-http-1.4.9.jar.
I replaced it with android-async-http-1.4.8.jar.

Thanks. :+1:

**Comment by jackson-therasoft** [comment]
This error comes when i click login button.

10-27 11:24:37.503: E/AndroidRuntime(23706): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.pexip.example-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libjingle_peerconnection_so.so"

but the libjingle_peerconnection_so.so file is available in jni folder.
4 files there.
jni->arm64-v8a->ibjingle_peerconnection_so.so
jni->arm64-v8a->ibjingle_peerconnection_so.so

**Comment by hanimustafa** [comment]
Try adding the jni folder in the nativeLibrariesDirectories list

**Comment by jackson-therasoft** [comment]
Yes. I added. And it works.

It shows selfview on the screen.

Thank you guys. Thanks for your support. :)

**Comment by ianmorty** [comment]
closing this now as you're all up and running.  Thanks for the help @xiaozhubenben
