### ISSUE TITLE
[iOS] Video quality issues

### ISSUE THREAD

**Issue by ivanbellalopez** [pexip/pexkit-sdk#41]
Under the same network conditions and using more or less same camera capabilities seems that Android provides better video quality than iOS.

Is there a way to modify this? I guess `videoResolution` property affects only the quality of the received video but the sent one because does not seem to change anything.

**Comment by ianmorty** [comment]
Hi @ivanbellalopez.  Video quality is a very subjective matter.  If we ignore the obvious differences in the two completely different platforms, physical camera differences, lenses, display screens and brightness and image processing capabilities provided by the different operating systems could you provide examples of your network setup and comparative images ?

You can alter the `videoResolution` as mentioned and that will set the bandwidth appropriately.  By default, in iOS, connected to WiFi we use 448p@1172kbps and wcif@384kbps on cellular.  We've kept them low as older hardware struggles to keep up with higher bitrates and resolutions and provides a poor experience.

**Comment by ivanbellalopez** [comment]
Thanks @ianmorty. The presets for `videoResolution` makes sense as they are. Tried again today and quality is similar for both. 

Sorry about that.

**Comment by ianmorty** [comment]
No problem :-)

**Comment by VivaLosDoyers** [comment]
@ianmorty check out the attached screenshot, which compares Hangouts and Pexip on an iPhone 6S over LTE. My connection to LTE in my office is ~38 Mbps. As you can see, there's a **significant** difference in encoding quality between the two. As far resource load goes, I installed Hangouts on a 5th gen iPod touch, an older and slower device. Hangouts is able to provide video at this level without rendering the device useless.

Based on this, I would say there's some room for improvement here.

![screen shot 2016-07-22 at 12 01 56 pm](https://cloud.githubusercontent.com/assets/20602881/17068174/4b1674f2-5004-11e6-85c6-7cd80678333b.png)

**Comment by ianmorty** [comment]
Yep.  As mentioned above that'll be a 448p call.  Is your hangouts media running peer-to-peer or via an MCU ?  Don't forget you're running through your service provider and down to a transcoding MCU too !  Trying bumping the `conference.videoResolution` up and see what you get.  As for hardware, we're using Googles libwebrtc framework from Chrome so it's the same engine doing the processing under the covers.  They might be running a later version and also know some black magic about making it run fast on certain hardware.

**Comment by xiefangzhenz** [comment]
Android provides better video quality than iOS when video with PC.How can I solve this issues?

**Comment by jfowens** [comment]
@xiefangzhenz: "out of the box," the SDK will limit the resolution to wCIF on cellular data and w448p on wifi. Feel free to bump up the resolution via `conference.videoResolution` to improve the outbound resolution from the SDK.

**Comment by xiefangzhenz** [comment]
@jfowens   thank you very much!

**Comment by jfowens** [comment]
Happy to help.

**Comment by yindalei00** [comment]
Happy to help. but  where are SDK API
