### ISSUE TITLE
Portrait oriented video is only partially received by other participants

### ISSUE THREAD

**Issue by miguelsanchez** [pexip/pexkit-sdk#45]
When a video is taken by a device in a portrait or vertical mode, other participants only received the central part of that video instead of the full vertical view inscribed in a pillar box view. Since that seems like a server side issue, it would be nice to have some information about what is the part of the video that will not be cropped out so that we can mask the local video and allow users to know what is actually visible by other participants in the conference.

I'll illustrate the current issue with the following snapshots:

Emitter (consider the video with a painting in it as the local video):
![img_0852](https://cloud.githubusercontent.com/assets/777163/17897156/747128e8-6953-11e6-832b-fad00b5f8b46.PNG)

Receiver:
![img_0084](https://cloud.githubusercontent.com/assets/777163/17897190/927eca2a-6953-11e6-8ae9-a80001c8f9d9.PNG)

Whereas when the device is in landscape mode most of the video is transmitted. I say most, because I've noticed that the borders of the video are also cropped.

![img_0853](https://cloud.githubusercontent.com/assets/777163/17897294/f184bb6a-6953-11e6-8d6c-1fad3bd0a871.PNG)

Receiver (this snapshot wasn't very well done but while taking it I could see the painting from side to side):
![img_0085](https://cloud.githubusercontent.com/assets/777163/17897300/f55e412a-6953-11e6-8db2-9687d31d0f9a.PNG)

**Comment by ianmorty** [comment]
These SDK's are now deprecated and i'd suggest moving over to the new methods as outlined in the guides thus giving you full control over every aspect of the connection.

Specifically, make sure you review sections 2.6.2 through 2.6.5
