### ISSUE TITLE
PexKit with XCode 8

### ISSUE THREAD

**Issue by VTJamie** [pexip/pexkit-sdk#49]
I tried to use a project that previously had the xcode 7 build version of PexKit.  When I upgraded to the latest PexKit framework (built with XCode 8) I started getting ConferenceDelegate not found compilation errors.  Is there a known way to fix this, or is something wrong in my project?

**Comment by xiangshun110** [comment]
i am problem ：No such module 'PexKit'

**Comment by ianmorty** [comment]
Is this still an issue for you ?
