### ISSUE TITLE
Android example app cannot run  on samsung S4 

### ISSUE THREAD

**Issue by xiaozhubenben** [pexip/pexkit-sdk#5]
Hi,
It seemed samsung S4 (4.4.2) cannot run  android example ,it throwed same exception as 
http://stackoverflow.com/questions/26504742/open-gl-bad-config-error-on-samsung-s4

10-28 09:36:46.161: E/AndroidRuntime(20878): FATAL EXCEPTION: GLThread 977
10-28 09:36:46.161: E/AndroidRuntime(20878): Process: com.xxx.webrtcapp, PID: 20878
10-28 09:36:46.161: E/AndroidRuntime(20878): java.lang.RuntimeException: createContext failed: EGL_BAD_CONFIG
10-28 09:36:46.161: E/AndroidRuntime(20878): 	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1201)
10-28 09:36:46.161: E/AndroidRuntime(20878): 	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1192)
10-28 09:36:46.161: E/AndroidRuntime(20878): 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1042)
10-28 09:36:46.161: E/AndroidRuntime(20878): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1409)
10-28 09:36:46.161: E/AndroidRuntime(20878): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

Does anybody  know how to fix this  problem?
Another android phone (samsung Note 3 ,android 5.0)  ran  example app successfully

thanks.

**Comment by ianmorty** [comment]
so is that something you can change in your app ?  I'll have a look at the code to see if it's something we can help with lower down in pexkit.

**Comment by ianmorty** [comment]
@xiaozhubenben are you still seeing issues with this ?

**Comment by xiaozhubenben** [comment]
yes. 
It  seemed the Android SDK was not updated recently ?

**Comment by ianmorty** [comment]
No we're not seeing similar things here at the moment

**Comment by xiaozhubenben** [comment]
hi,I have found the solution to fix this .
just as  this link metioned:
http://stackoverflow.com/questions/26504742/open-gl-bad-config-error-on-samsung-s4

In PexKit create  funtion, a line code: 
remoteVideoView.setEGLContextClientVersion(2);
must added before 
remoteVideoView.setEGLConfigChooser(8, 8, 8, 8, 16, 0);

**Comment by wuurrd** [comment]
This is in the newest sdk version.
