### ISSUE TITLE
[Android] Ability to set video resolution?

### ISSUE THREAD

**Issue by havardholvik** [pexip/pexkit-sdk#50]
When running my app using Pexkit SDK (2016-06-28) in the simulator, the app receives video in 720p from Pexip. When running the app on device (Galaxy Note 3 and Xperia Z5) the received video is in 352x288 (devices are connected to wifi). I also notice the emulator is using VP8 and the devices are using H264 for video coding (looked at Pexip management interface).

Is it possible to set resolution somehow using the SDK? If not, how is the logic for setting/determining video resolution/codec in the current version of the SDK?

**Comment by Dari-K** [comment]
Hi @havardholvik, currently this can't be set using the SDK. I believe the SDK currently uses whatever the default width and height settings are for a new MediaConstraints object, and similarly uses a method called getLocalRenderer, which I imagine determines the codec used.

**Comment by ianmorty** [comment]
These SDK's are now deprecated and i'd suggest moving over to the new methods as outlined in the guides thus giving you full control over every aspect of the connection.
