### ISSUE TITLE
Feature Request: Reporting streams packet loss using WebRTC getStats (via libjingle bindings)

### ISSUE THREAD

**Issue by zaichang** [pexip/pexkit-sdk#53]
We would like the ability to monitor or be notified of changes in connection quality to the Pexip server. for both iOS and Android The end goal for us is to be able to switch video resolution and/or modalities depending on network conditions, and using the metric of outgoing and incoming packet loss 

WebRTC's getStats method gives us that ability, and there's [an example for the web SDK here](http://www.w3.org/TR/webrtc-stats/#example-of-a-stats-application). And libjingle for both iOS and Android already seem to have method of querying it:
- On iOS, `RTCPeerConnection.h` has a `- (BOOL)getStatsWithDelegate (id<RTCStatsDelegate>)delegate mediaStreamTrack:(RTCMediaStreamTrack*)mediaStreamTrack statsOutputLevel:(RTCStatsOutputLevel)statsOutputLevel` method
- On Android, `PeerConnection.java` has `public boolean getStats(StatsObserver observer, MediaStreamTrack track)`

So it seems it is a matter of adding a method in the Pexkit to hook into them and report back the stats. For example a simple delegate method that reports the packet loss % for a given stream should be sufficient.

**Comment by ianmorty** [comment]
As you know, these SDK's are now deprecated and we're no longer adding feature requests into them.  You can now build your own WebRTC with these stats enabled and plug into them directly from your app with the help of the guides here on this site.
