### ISSUE TITLE
Frame rate from iPhone 7 is very low 

### ISSUE THREAD

**Issue by miguelsanchez** [pexip/pexkit-sdk#55]
We've been testing the latest SDK (7.7.4) and also one previous one (7.5.4) on a new iPhone 7 and we've noticed a similar issue that is not happening when the app is run in older devices (iPhone 6 Plus running iOS 10.1, iPad Pro running iOS 9.3.5).

After a few seconds of transmission, any video sent from an iPhone 7 starts to degrade, low its frame rate and even stale (received as static gray image). This effect can be easily reproduced by recording a very dynamic scene, forcing the video to change frequently. It's not so noticeable in a more static scene.

Audio is OK during that time.

**Comment by ianmorty** [comment]
Suspect this is a subtle problem in the old version of the WebRTC framework in the SDK.  These SDK's are now deprecated and i'd suggest moving over to the new methods as outlined in the guides thus giving you full control over every aspect of the connection.  You can then build using the latest WebRTC libraries too.
