### ISSUE TITLE
[iOS] Crash when camera permissions are disabled

### ISSUE THREAD

**Issue by ivanbellalopez** [pexip/pexkit-sdk#56]
When camera permissions are disabled Pexkit crashes if you still want to see the video input.

(1) In our implementation we check for the permissions. If user has denied/restricted the camera access we set `videoMute = true` and `videoSelfView = nil` but it still crashes. 

The only solution I found was to  set also `videoView = nil`. It works but, of course, user can't see anything anymore.

This happens when when permission is denied. On the other hand if it's the first time and user is asked for permission and the answer is no, doing (1) works perfectly and user can see the video input.

The stack trace I have is 
```

PexKit`cricket::ChannelManager::GetSupportedFormats_w:
    0x100f1f9f8 <+0>:  stp    x20, x19, [sp, #-32]!
    0x100f1f9fc <+4>:  stp    x29, x30, [sp, #16]
    0x100f1fa00 <+8>:  add    x29, sp, #16              ; =16 
    0x100f1fa04 <+12>: mov    x19, x2
    0x100f1fa08 <+16>: mov    x0, x1
    0x100f1fa0c <+20>: bl     0x100ea1d34               ; cricket::VideoCapturer::GetSupportedFormats() const
    0x100f1fa10 <+24>: cbz    x0, 0x100f1fa30           ; <+56>
    0x100f1fa14 <+28>: cmp    x0, x19
    0x100f1fa18 <+32>: b.eq   0x100f1fa30               ; <+56>
->  0x100f1fa1c <+36>: ldp    x1, x2, [x0]
    0x100f1fa20 <+40>: mov    x0, x19
    0x100f1fa24 <+44>: ldp    x29, x30, [sp, #16]
    0x100f1fa28 <+48>: ldp    x20, x19, [sp], #32
    0x100f1fa2c <+52>: b      0x100ddfe1c               ; std::__1::enable_if<(__is_forward_iterator<cricket::VideoFormat*>::value) && (is_constructible<cricket::VideoFormat, std::__1::iterator_traits<cricket::VideoFormat*>::reference>::value), void>::type std::__1::vector<cricket::VideoFormat, std::__1::allocator<cricket::VideoFormat> >::assign<cricket::VideoFormat*>(cricket::VideoFormat*, cricket::VideoFormat*)
    0x100f1fa30 <+56>: ldp    x29, x30, [sp, #16]
    0x100f1fa34 <+60>: ldp    x20, x19, [sp], #32
    0x100f1fa38 <+64>: ret    

```

This issue is important because it compromises the usage of the videoconference to become just an audio only situation...

**Comment by ianmorty** [comment]
The SDK assumes you are either a control only participant, audio only participant or full AV participant and you shouldn't try to mix these up.  

These SDK's are now deprecated and i'd suggest moving over to the new methods as outlined in the guides thus giving you full control over every aspect of the connection.
