### ISSUE TITLE
Ability to set bandwith value ?

### ISSUE THREAD

**Issue by misu-rg** [pexip/pexkit-sdk#57]
Hello,

can we set custom value for bandwidth in Android and iOS SDKs ?

We have this option for PexRTC js SDK  :

bandwidth	|   Maximum bandwidth (in kbps) for up and down stream (can be null).

**Comment by ianmorty** [comment]
SDK bandwidth is controlled through the `resolution` parameter on the `Conference` object.  These SDK's are now deprecated and i'd suggest moving over to the new methods as outlined in the guides thus giving you full control over every aspect of the connection.
