### ISSUE TITLE
Failed To Post media Escalation

### ISSUE THREAD

**Issue by bens12** [pexip/pexkit-sdk#6]
ERROR Conference: Failed to post media escalation: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7f895bd4fdd0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https:...................................., NSErrorFailingURLKey=https:........................, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}
Media escalation status was Unknown error

...........
The sample project is compiled successfully, at last i got this error can you please help me why this error occurs.
...........

**Comment by ianmorty** [comment]
so the error is indicating that the call to the MCU to escalate media timed out.  what are you connecting too ?

**Comment by bens12** [comment]
connecting to our video server.

**Comment by ianmorty** [comment]
ok, so then i'd start looking at logs on your PEXIP server to correlate events between your REST calls to the server and what it thinks is happening to the call.  Have a look at support and administration logs more in depth information.  Also make sure your consulting http://docs.pexip.com for information on configuration of your servers.

**Comment by bens12** [comment]
2015-10-28 15:11:25.656 Demo1[2447:92722] Communications error: <OS_xpc_error: <error: 0x110ebfb40> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x110ebfef0> { length = 22, contents = "Connection interrupted" }
}>


getting this error also at last.

**Comment by ianmorty** [comment]
@bens12 have you got any further with this - seems like network connectivity issues on the surface

**Comment by ianmorty** [comment]
@bens12 let's close this until you can get some more information
