### ISSUE TITLE
iOS example

### ISSUE THREAD

**Issue by charleswlee** [pexip/pexkit-sdk#60]
The iOS example is not sending audio or video I can only hear remote audio and see remote video streams.  

Also I do not see a way to present the local videoSelfView as before.

**Comment by ianmorty** [comment]
So this may be related to the constraints being sent into the framework - WebRTC isn't very helpful when it fails.  Try setting a different resolution or even removing the min/max width settings from the constraints.

As for self view, this is something you can add yourself.  You just need to hookup a RTCEAGLVideoView in your storyboard to a video track e.g. `self.videoTrack?.add(self.videoSelfView)`

**Comment by charleswlee** [comment]
@ianmorty by switching to HD I was able to connect with the iOS example and the self.videoTrack?.add(self.videoSelfView) with the RTCEAGLVideoView worked to get the local video

**Comment by ianmorty** [comment]
👍 i'll tweak the example to remove the default constraints and update the example docs to include the bit about self view.
