### ISSUE TITLE
iOS back camera in landscape upside down stream

### ISSUE THREAD

**Issue by charleswlee** [pexip/pexkit-sdk#61]
Using the new example when in landscape and using the back camera the video stream is upside down.

**Comment by charleswlee** [comment]
Any updates on this?  I tried the latest WebRTC.framework and the problem gets worse. The front camera doesn't follow the orientation of the device.   Did you build and modify WebRTC framework that is posted in the example?

**Comment by ianmorty** [comment]
There are patches to the WebRTC code as outlined in section 4.1.1 of the guides.
