### ISSUE TITLE
Poor video quality out on iOS

### ISSUE THREAD

**Issue by charleswlee** [pexip/pexkit-sdk#62]
I am experiancing poor video quality from the Demo app on iOS for video being sent from the device.  The quality of the incoming video is fine.   Video is set to 720p

**Comment by ianmorty** [comment]
This is just a demo app.  It is purely there to show how one could structure an application.  I'd suggest starting to look at Section 2.6.5 of guide to get a better understanding of what is happening under the covers and how you should go about changing it to suit your application.
