### ISSUE TITLE
Cannot resolve method setAudioMute(boolean) + compile error

### ISSUE THREAD

**Issue by marekfoltyn** [pexip/pexkit-sdk#7]
Hi,
I am trying to compile the Android example App on Android Studio (OS X), but I have two problems:

Firstly, conference.setAudioMute(true) seems to be undefined:
<img width="939" alt="snimek obrazovky 2015-12-18 v 10 50 59" src="https://cloud.githubusercontent.com/assets/6121995/11894253/4252bf76-a576-11e5-9240-60718e0448e4.png">

So I tried to comment the lines with this errors and compiled again. However, this is the result:
<img width="1330" alt="snimek obrazovky 2015-12-18 v 10 56 25" src="https://cloud.githubusercontent.com/assets/6121995/11894254/4279bfc2-a576-11e5-985c-dcc567bec3f3.png">

Is the error in my PC or in the SDK? Thanks.

Marek

**Comment by ianmorty** [comment]
The latest SDK now has audioMute back in - you'll need to re-add the sdk to the examples to get it going again.  Make sure you gradle sync before running again.

Rgds,

Ian

**Comment by ianmorty** [comment]
Everything all OK now with the latest SDK ?  Closing unless you still have problems.

**Comment by marekfoltyn** [comment]
Yes, now it is ok. Thank you!
